### ISSUE TITLE
CI not automatically publishing

### ISSUE THREAD

**Issue by lengau** [snapcrafters/ruff#50]
The `publish` action in CI isn't automatically running after the bot pushes updates

**Comment by soumyaDghosh** [comment]
@lengau Is it still happening?

**Comment by lengau** [comment]
@soumyaDghosh unfortunately yes - I had to kick off the run for version 0.6.8 manually: https://github.com/snapcrafters/ruff/actions/workflows/release-to-candidate.yaml

**Comment by lucyllewy** [comment]
I suspect this is because you're using the internal GitHub token for commit permissions. You need to use `SNAPCRAFTERS_BOT_COMMIT` because the internal one is designed by GitHub to not cause any push-triggered actions to run when using it to push changes to a branch.

**Comment by lengau** [comment]
Thanks @lucyllewy - that checks out! Fixed now.
